# Generated by Django 5.0.4 on 2024-05-05 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150, verbose_name='email')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Улица')),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер дома')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Модель')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата выхода на рынок')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_type', models.PositiveIntegerField(choices=[(0, 'Завод'), (1, 'Магазин'), (2, 'ИП')], verbose_name='Тип')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('debt', models.FloatField(blank=True, null=True, verbose_name='Задолженность перед поставщиком')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronics.contact', verbose_name='Контакты')),
                ('products', models.ManyToManyField(to='electronics.product', verbose_name='Продукты')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='electronics.seller', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
    ]
